# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aprendiz de front-end
email: 2pedro8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Há cerca de um ano comecei a trabalhar como desenvolvedor front-end e
  recentemente tenho me deparado com a necessidade de registrar minhas
  descobertas, observações, para poder amadurecer na área. Este blog será
  o espaço para isto.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zapiano.com.br" # the base hostname & protocol for your site
twitter_username: zapiano
github_username:  zapiano
comments: true

# Build settings
markdown: kramdown
